name: CI

on: [push, pull_request]

jobs:
  build_ps2:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download/Copy RB2 Songs
        run: |
          chmod +x dependencies/linux/gdrive
          dependencies/linux/gdrive account import dependencies/linux/gdrive_key.tar
          dependencies/linux/gdrive files download 1gTMkLScBkENtSk2EHDweMmlfMi9XMUGK --recursive --destination ./
          mv ./rb2dxsongs/* ./_ark/songs -f

      - name: Build ARK
        run: |
          chmod +x dependencies/linux/arkhelper
          chmod +x dependencies/linux/dtab
          chmod +x dependencies/linux/superfreq
          dependencies/linux/arkhelper dir2ark ./_ark ./_build/ps2/gen -n "MAIN" -e -v 4 -s 4000000000
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB2DX-PS2
          path: _build/ps2
  build_ps2_ce:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build ARK
        run: |
          chmod +x dependencies/linux/arkhelper
          chmod +x dependencies/linux/dtab
          chmod +x dependencies/linux/superfreq
          dependencies/linux/arkhelper dir2ark ./_ark ./_build/ps2/gen -n "MAIN" -e -v 4 -s 4000000000
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB2DXCE-PS2
          path: _build/ps2
